# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectFolder: '$(Build.Repository.LocalPath)\src\EncryptionCertificateStoreProvider'
  testFolder: '$(Build.Repository.LocalPath)\tests\EncryptionCertificateStoreProviderTests'

steps:

- task: DownloadSecureFile@1
  name: strongNameSigningCert
  inputs:
    secureFile: CertificateKeyStoreProvider.snk
    retryCount: 5

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Copying strong name signing certificate to project directory '$(projectFolder)'..."
      Copy-Item $(strongNameSigningCert.secureFilePath) -Destination $(projectFolder)
      Write-Host "Copying strong name signing certificate to test directory '$(testFolder)'..."
      Copy-Item $(strongNameSigningCert.secureFilePath) -Destination $(testFolder)

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'xtrimmer-github'
    scannerMode: 'MSBuild'
    projectKey: 'Xtrimmer_EncryptionCertificateStoreProvider'
    projectName: 'EncryptionCertificateStoreProvider'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    codeCoverageEnabled: True

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'